name: FastingTracker
options:
  bundleIdPrefix: com.oalexoprea
  minimumXcodeVersion: "15.0"
targets:
  FastingTracker:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
        excludes:
          - "project.yml"
          - "FastingTracker"
          - ".github/**"
          - "FastingTracker_test"
