name: FastingTracker
options:
  bundleIdPrefix: com.oalexoprea
  minimumXcodeVersion: "15.0"
targets:
  FastingTracker:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      DEVELOPMENT_TEAM: MT4VPZ4AVA
      GENERATE_INFOPLIST_FILE: true
      CODE_SIGN_IDENTITY: "Apple Distribution"
    sources:
      - path: .
        excludes:
          - "project.yml"
          - "FastingTracker"
          - ".github/**"
          - "FastingTracker_test"
