name: FastingTracker
options:
  bundleIdPrefix: com.oalexoprea
  minimumXcodeVersion: "15.0"
targets:
  FastingTracker:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      DEVELOPMENT_TEAM: MT4VPZ4AVA
      GENERATE_INFOPLIST_FILE: true
      CURRENT_PROJECT_VERSION: "9"
      MARKETING_VERSION: "1.0"
      TARGETED_DEVICE_FAMILY: "1"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_KEY_DTSDKName: iphoneos26.1
      INFOPLIST_KEY_DTXcode: "1610"
      INFOPLIST_KEY_DTXcodeBuild: "16B40"
      INFOPLIST_KEY_DTSDKBuild: "26B40"
    sources:
      - path: .
        excludes:
          - "project.yml"
          - "FastingTracker"
          - ".github/**"
          - "FastingTracker_test"
          - "generate_assets.swift"
      - path: Assets.xcassets
